export const els = {
  clearSearch: document.querySelector("#clearSearch"),
  error: document.querySelector("#loadingError"),
  nextVariant: document.querySelector("#nextVariant"),
  prevVariant: document.querySelector("#prevVariant"),
  searchInput: document.querySelector("#searchInput"),
  searchMeta: document.querySelector("#searchMeta"),
  searchResults: document.querySelector("#searchResults"),
  searchToggle: document.querySelector("#searchToggle"),
  taskNav: document.querySelector("#taskNav"),
  tasks: document.querySelector("#tasks"),
  variantSelect: document.querySelector("#variantSelect"),
  variantSubtitle: document.querySelector("#variantSubtitle"),
  variantTitle: document.querySelector("#variantTitle"),
};
